export interface FactorCacheRecordVO {
  id: string | number;
  cacheVersionId?: string | number;
  factorTableCode?: string;
  factorCode?: string;
  factorName?: string;
  factorCategory?: string;
  factorValue?: number;
  factorUnit?: string;
  factorKey?: string;
  emissionSourceName?: string;
  emissionSourceNameEn?: string;
  fuelMaterialCategory?: string;
  sourceUnit?: string;
  co2?: number;
  ch4?: number;
  n2o?: number;
  hfcs?: number;
  pfcs?: number;
  sf6?: number;
  nf3?: number;
  applicableScope?: string;
  factorSource?: string;
  gwpCh4?: number;
  gwpN2o?: number;
  gwpHfcs?: number;
  gwpPfcs?: number;
  gwpSf6?: number;
  gwpNf3?: number;
  factorGwp?: number;
  versionProvinceCode?: string;
  factorVersion?: string;
  divisionCode?: string;
  divisionName?: string;
  regionName?: string;
  provinceFactor?: number;
  regionFactor?: number;
  nationalFactor?: number;
  nonFossilExcludedFactor?: number;
  nationalFossilPowerFactor?: number;
  rowNo?: number;
  fuelLevel1?: string;
  fuelLevel2?: string;
  fuelLevel3?: string;
  fuelLevel4?: string;
  lowerHeatValue?: number;
  lowerHeatValueCv?: number;
  co2Factor?: number;
  co2FactorCv?: number;
  gwpValue?: number;
  convertedFactor?: number;
  sourceRef?: string;
  enabledFlag?: boolean;
  syncedTime?: string;
}

export interface FactorCacheRecordForm extends BaseEntity {
  id?: string | number;
  cacheVersionId?: string | number;
  factorTableCode?: string;
  factorCode?: string;
  factorName?: string;
  factorCategory?: string;
  factorValue?: number;
  factorUnit?: string;
  factorKey?: string;
  emissionSourceName?: string;
  emissionSourceNameEn?: string;
  fuelMaterialCategory?: string;
  sourceUnit?: string;
  co2?: number;
  ch4?: number;
  n2o?: number;
  hfcs?: number;
  pfcs?: number;
  sf6?: number;
  nf3?: number;
  applicableScope?: string;
  factorSource?: string;
  gwpCh4?: number;
  gwpN2o?: number;
  gwpHfcs?: number;
  gwpPfcs?: number;
  gwpSf6?: number;
  gwpNf3?: number;
  factorGwp?: number;
  versionProvinceCode?: string;
  factorVersion?: string;
  divisionCode?: string;
  divisionName?: string;
  regionName?: string;
  provinceFactor?: number;
  regionFactor?: number;
  nationalFactor?: number;
  nonFossilExcludedFactor?: number;
  nationalFossilPowerFactor?: number;
  rowNo?: number;
  fuelLevel1?: string;
  fuelLevel2?: string;
  fuelLevel3?: string;
  fuelLevel4?: string;
  lowerHeatValue?: number;
  lowerHeatValueCv?: number;
  co2Factor?: number;
  co2FactorCv?: number;
  gwpValue?: number;
  convertedFactor?: number;
  sourceRef?: string;
  enabledFlag?: boolean;
  syncedTime?: string;
}

export interface FactorCacheRecordQuery extends PageQuery {
  cacheVersionId?: string | number;
  factorTableCode?: string;
  factorCode?: string;
  factorName?: string;
  factorCategory?: string;
  enabledFlag?: boolean;
  params?: any;
}
